name: Makefile CI

on:
  push:
    branches:
      - master
      - memoize
  pull_request:
    branches: 
      - master
      - memoize
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update system
      run: sudo apt-get update

    - name: Install dependencies
      run: sudo apt-get install texlive

    - name: Build core documents for all workshops
      run: make most
